<a href="https://colab.research.google.com/github/kamal-ganwani/Python_Lambda_Tutorial/blob/main/PF_W4D2_20_01_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lambda arguments:expression

In [ ]:
def add_(x,y):
  return x+y

In [ ]:
add_(5,4)

9

In [ ]:
add=lambda x,y:x+y

In [ ]:
add(6,7)

13

In [ ]:
A=lambda x:x**2

In [ ]:
A(4)

16

In [ ]:
def square_(x):
  return x**2

In [ ]:
square_(4)

16

In [ ]:
''' Higher Order Function

1. User defined Higher Order Functions
2. Predefined Higher Order Functions

'''

' Higher Order Function\n\n1. User defined Higher Order Functions\n2. Predefined Higher Order Functions\n\n'

In [ ]:
sum([1,2,3])

6

In [ ]:
def apply_function(x,y,z,a):
  return z(x,y),a(x,y)

In [ ]:
add=lambda x,y:x+y
sub=lambda x,y:x-y

In [ ]:
apply_function(3,4,add,sub)

(7, -1)

In [ ]:
''' Predefined Higher Order Functions

1.map
2.filter
3.reduce

'''

' Predefined Higher Order Functions\n\n1.map\n2.filter\n3.reduce\n\n'

In [ ]:
x=[1,2,3,4,5]

s_x=list(map(square,x))   #list(map(int,input().split())
s_x

[1, 4, 9, 16, 25]

In [ ]:
def square(x):
  return x**2

In [ ]:
x=[1,2,3,4]

even=list(map(lambda x:x%2==0,x))
even

[False, True, False, True]

In [ ]:
x=[1,2,3,4,5]

In [ ]:
s_x=[]  #General Method

for i in x:
  s_x.append(i**2)
s_x

[1, 4, 9, 16, 25]

In [ ]:
s_x=[i**2 for i in x] #List Comprehension
s_x

[1, 4, 9, 16, 25]

In [ ]:
s_x=list(map(lambda x:x**2,x)) #Map Method
s_x

[1, 4, 9, 16, 25]

In [ ]:
x=(1,2,3,4,5)
s_x=tuple(map(lambda x:x**2,x)) #Map Method
s_x

(1, 4, 9, 16, 25)

In [ ]:
x=[1,2,3,4,5]
even=list(map(lambda x:x%2==0,x))
even

[False, True, False, True, False]

In [ ]:
3%2==0

False

In [ ]:
even=list(filter(lambda x:x%2==0,x))
even

[2, 4]

In [ ]:
Age=[23,34,2,55,1,34,67,89,1000,23]

In [ ]:
Age_=list(filter(lambda x:x>=18 and x<=120,Age))
Age_

[23, 34, 55, 34, 67, 89, 23]

In [ ]:
x=[1,2,3,4,5]

In [ ]:
sum(x)

15

In [ ]:
max(x)

5

In [ ]:
min(x)

1

In [ ]:
l=[1,2,3,4,5]

In [ ]:
from functools import reduce

sum_x=reduce(lambda x,y:x+y,l)
sum_x

15

In [ ]:
sum(l)

15

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x=[1,'A',1.4]
y=np.array([1,2,3])

In [ ]:
type(x)

list

In [ ]:
type(y)

numpy.ndarray

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
numpy.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [ ]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros([3,2],dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.ones([3,2],dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.full(5,7) #full(no of x,x)

array([7, 7, 7, 7, 7])

In [ ]:
np.full([3,4],10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x.shape

(3, 3)

In [ ]:
x.ndim

2

In [ ]:
x.size

9

In [ ]:
y=np.array([1,2,3,4])

In [ ]:
y.ndim

1

In [ ]:
y.shape

(4,)

In [ ]:
y.size

4

In [ ]:
x=np.array([])

In [ ]:
x.size

0

In [ ]:
x.ndim

1

In [ ]:
x.shape

(0,)

In [ ]:
 x=np.array([
     [
         [1,2,3],
         [4,5,6],
         [7,8,9]
     ],
     [
         [11,22,33],
         [44,55,66],
         [77,88,99]
     ]
 ])

In [ ]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 3, 3)

In [ ]:
x.size

18

In [ ]:
np.arange(10) #arange(start=0,stop=?,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [ ]:
np.linspace(1,2,14) #linspace(start=?,stop=?(inclusive),no of values you want from start to stop)

array([1.        , 1.07692308, 1.15384615, 1.23076923, 1.30769231,
       1.38461538, 1.46153846, 1.53846154, 1.61538462, 1.69230769,
       1.76923077, 1.84615385, 1.92307692, 2.        ])

In [ ]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [ ]:
data = np.array([2, 4, 4, 4, 5, 5, 7, 9])

In [ ]:
np.mean(data)

5.0

In [ ]:
np.median(data)

4.5

In [ ]:
np.var(data)

4.0

In [ ]:
np.std(data)

2.0

In [ ]:
x=np.array([1,2,3])
y=np.array([2,3,4])

In [ ]:
x/y

array([0.5       , 0.66666667, 0.75      ])

In [ ]:
round(2/3,3)

0.667

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [ ]:
x*y

array([ 4, 10, 18])

In [ ]:
np.dot(x,y)

32

In [ ]:
x=np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
  ])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[2][2]

9

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [ ]:
x>3

array([False, False, False,  True,  True])